"""added last message stamp

Revision ID: 0522f9a096d4
Revises: 148def4e164b
Create Date: 2023-12-22 04:23:39.790472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0522f9a096d4"
down_revision: Union[str, None] = "148def4e164b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_sent", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "messages", ["last_sent"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "last_sent")
    # ### end Alembic commands ###
