"""changed new column name to more understandable

Revision ID: fdb6e3981cec
Revises: 0522f9a096d4
Create Date: 2023-12-22 15:35:43.427164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb6e3981cec'
down_revision: Union[str, None] = '0522f9a096d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_received', sa.Integer(), nullable=True))
    op.drop_constraint('users_last_sent_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'messages', ['last_received'], ['id'])
    op.drop_column('users', 'last_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_sent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_last_sent_fkey', 'users', 'messages', ['last_sent'], ['id'])
    op.drop_column('users', 'last_received')
    # ### end Alembic commands ###
